Update library doc page with 'Standard' field removed
boostorg/website pull request #585
Opened 2021-01-09 23:20 UTC by novoio

- Remove 'Standard' field from each library info
- Remove 'Standard Proposals' and 'TR1 libraries' from sort categories
- Add 'C++ Minimum' to sort categories

2021-01-09 23:27 UTC, glenfe requested changes
If we're removing std-proposal and std-tr1, they should be removed in all places in this file and others.

2021-01-09 23:27 UTC, glenfe commented on doc/libraries.php
> +        // 'std-tr1' => 'TR1 libraries',
Don't comment it out, just delete it

2021-01-09 23:27 UTC, glenfe commented on doc/libraries.php
>          'std-tr1' => 'STD::TR1',
Shouldn't these two be removed?

2021-01-09 23:33 UTC, novoio commented on doc/libraries.php
>          'std-tr1' => 'STD::TR1',
@glenfe Just done your feedback

2021-01-10 02:03 UTC, glenfe commented
I pointed a few more places out in the channel:

* https://github.com/boostorg/website/blob/739c70cb172f41c03ac44e2e8497e3e6a5e29c61/doc/libraries.php#L245-L250
* https://github.com/boostorg/website/blob/739c70cb172f41c03ac44e2e8497e3e6a5e29c61/common/code/boost_utility.php#L59-L63
* https://github.com/boostorg/website/blob/739c70cb172f41c03ac44e2e8497e3e6a5e29c61/common/code/boost_libraries.php#L119-L129

2021-01-10 04:18 UTC, merged