Grammar corrections in community folder
boostorg/website pull request #593
Opened 2021-02-05 19:15 UTC by DamianArado

Grammar corrections in 20 files in community folder with 196 additions and 204 deletions.

2021-02-27 18:56 UTC, mloskot requested changes

2021-02-27 18:56 UTC, mloskot commented on community/committee.html
> +              Members of PL22.16 (the INCITS/ANSI committee) or of WG21 (ISO)
The `a` is incorrect in this context. The WG21 is one an known.

2021-02-27 18:56 UTC, mloskot commented on community/counted_body.html
> +                (a specialization of LAZY EVALUATION) requires the use of a
Well, I'd argue this change is incorrect  ;P

2021-02-27 18:56 UTC, mloskot commented on community/counted_body.html
> +              additional constraints. Compile-time polymorphism, as its name
Please, revert this part

2021-02-27 18:56 UTC, mloskot commented on community/counted_body.html
> +              support selection of the appropriate type of safe version of the
Rather `type-safe`

2021-02-27 18:56 UTC, mloskot commented on community/error_handling.html
> +              to be canceled gracefully. On the other hand, it would
Thin ice!

2021-02-27 18:56 UTC, mloskot commented on community/error_handling.html
> +                need to make a coherent message for users. For
Hmm?

2021-02-27 18:56 UTC, mloskot commented on community/generic_programming.html
> +              <p>Andrei's description of policy classes suggests that there
Wrong!

2021-02-27 18:56 UTC, mloskot commented on community/gsoc.html
> +        C++ programming competency tests on <a href="https://github.com/boostorg/wiki/wiki/Google-Summer-of-Code%3A-Overview">
Still needs reindentation

2021-02-27 18:56 UTC, mloskot commented on community/gsoc.html
>  </ul>
Please, do not mix fixes and reformatting in the same PR

2021-02-27 18:56 UTC, mloskot commented on community/gsoc_2006_boost_overview.html
> +              <p>Of these, additions (like for instance the min-cut/maxflow
Rather "max-flow min-cut algorithm"

2021-02-27 18:56 UTC, mloskot commented on community/review_schedule.html
> +    review.</p>
Reformatting does not belong here

2021-02-28 09:23 UTC, mloskot approved these changes

2021-03-02 14:20 UTC, glenfe requested changes

2021-03-02 14:20 UTC, glenfe commented on community/feature_model_diagrams.html
> +              <p>The graphical feature diagrams presented by C&amp; E are not
C&E was right, not "C& E"

2021-03-02 14:20 UTC, glenfe commented on community/feature_model_diagrams.html
> +              <p>A feature [C&amp; E 4.9.1] is "anything users or client
Again, no space here.

2021-03-02 14:20 UTC, glenfe commented on community/implementation_variations.html
> +              <p>Dietmar K&uuml; hl, one of the original boost.org
No space here.

2021-03-02 14:20 UTC, glenfe commented on community/official_library_maintainer_program.html
> +              all libraries must bundle with Boost releases
This is wrong. The original "bundled" is what we want here.

2021-03-02 14:49 UTC, DamianArado commented
Grammar corrections in 19 files in the community folder with 153 additions and 161 deletions.

2021-03-02 18:53 UTC, merged