Schedule reviews of MQTT and SQLite
boostorg/website pull request #877
Opened 2024-10-03 14:40 UTC by mloskot

Requested by @klemens-morgenstern

2024-10-04 16:51 UTC, klemens-morgenstern commented
Ivica Siladic submitted https://github.com/mireo/async-mqtt5

2024-10-04 21:06 UTC, mloskot commented
@klemens-morgenstern We need link to GitHub repo or even specific branch if non-default is supposed to be reviewed
and we also need Documentation link, for example, see https://github.com/boostorg/website/commit/6cb330902278cd09aa00ae641ef02d94356994e1

2024-10-05 00:13 UTC, klemens-morgenstern requested changes

2024-10-05 00:13 UTC, klemens-morgenstern commented on community/review_schedule.html
> +                        <li><a href="">Github</a></li>
```suggestion
                        <li><a href="https://github.com/mireo/async-mqtt5/tree/master">Github</a></li>
```

2024-10-05 00:13 UTC, klemens-morgenstern commented on community/review_schedule.html
> +                        <li><a href="">Documentation</a></li>
```suggestion
                        <li><a href="https://spacetime.mireo.com/async-mqtt5/>Documentation</a></li>
```

2024-10-05 00:13 UTC, klemens-morgenstern commented on community/review_schedule.html
> +                        <li><a href="">Documentation</a></li>
```suggestion
                        <li><a href="https://klemens.dev/sqlite/">Documentation</a></li>
```

2024-10-05 00:13 UTC, klemens-morgenstern commented on community/review_schedule.html
> +                        <li><a href="">Github</a></li>
```suggestion
                        <li><a href="https://github.com/klemens-morgenstern/sqlite">Github</a></li>
```

2024-10-05 09:35 UTC, merged